
xsb --nobanner -e "[testsc],run_tests([bongard]),halt." 
xsb --nobanner -e "[testsc],run_tests([bongardkeys]),halt." 
xsb --nobanner -e "[testsc],run_tests([hmmlearn]),halt." 
xsb --nobanner -e "[testsc],run_tests([shop]),halt." 
xsb --nobanner -e "[testsc],run_tests([shop1]),halt." 
xsb --nobanner -e "[testsc],run_tests([multiple_paths_simple_learning]),halt." 
xsb --nobanner -e "[testsc],run_tests([multiple_paths_learning]),halt." 
xsb --nobanner -e "[testsc],run_tests([bongard_ind]),halt." 
xsb --nobanner -e "[testsc],run_tests([bongard_fixed]),halt." 
xsb --nobanner -e "[testsc],run_tests([bongard_initial]),halt." 
xsb --nobanner -e "[testsc],run_tests([mach]),halt." 
xsb --nobanner -e "[testsc],run_tests([mach1]),halt." 
xsb --nobanner -e "[testsc],run_tests([registration]),halt." 
xsb --nobanner -e "[testsc],run_tests([registration1]),halt." 
